---
# Source: netbox/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.16.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  namespace: netbox
type: Opaque
data:
  postgresql-postgres-password: "c2xBa2F0ZEtCbQ=="
  postgresql-password: "Z3huSzBGQWRlUA=="
---
# Source: netbox/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-redis
  namespace: netbox
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-15.7.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "cmVkaXNfcGFzc3dvcmQ="
---
# Source: netbox/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-netbox
  labels:
    helm.sh/chart: netbox-4.1.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v3.2.8"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  email_password: ""
  napalm_password: ""
  secret_key: KGN6TTJJIn13OjYlUl97a2N6QnNyWkRocXpKRFxDMjhqcl1hSGQzdycxUlRXY3cgfClrdXlVYTRDIFM9
  superuser_password: YWRtaW4=
  superuser_api_token: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nw==